// players.js - Complete 365 NFL Fantasy Player Database (com espnId)
const defaultPlayers = [
    {"id": 1, "rank": 1, "name": "Jahmyr Gibbs", "team": "DET", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "S", "espnId": "4429795"},
    {"id": 2, "rank": 2, "name": "Bijan Robinson", "team": "ATL", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "S", "espnId": "4430807"},
    {"id": 3, "rank": 3, "name": "Ja'Marr Chase", "team": "CIN", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "S", "espnId": "4362628"},
    {"id": 4, "rank": 4, "name": "Puka Nacua", "team": "LAR", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "A", "espnId": "4426515"},
    {"id": 5, "rank": 5, "name": "Jaxon Smith-Njigba", "team": "SEA", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "A", "espnId": "4430878"},
    {"id": 6, "rank": 6, "name": "Christian McCaffrey", "team": "SF", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "A", "espnId": "3117251"},
    {"id": 7, "rank": 7, "name": "Amon-Ra St. Brown", "team": "DET", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "B", "espnId": "4374302"},
    {"id": 8, "rank": 8, "name": "Jonathan Taylor", "team": "IND", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "B", "espnId": "4242335"},
    {"id": 9, "rank": 9, "name": "CeeDee Lamb", "team": "DAL", "bye": 7, "pos": "WR", "posClass": "pos-wr", "tier": "B", "espnId": "4241389"},
    {"id": 10, "rank": 10, "name": "Justin Jefferson", "team": "MIN", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "B", "espnId": "4262921"},
    {"id": 11, "rank": 11, "name": "James Cook", "team": "BUF", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "B", "espnId": "4379399"},
    {"id": 12, "rank": 12, "name": "Ashton Jeanty", "team": "LV", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "B", "espnId": "4890973"},
    {"id": 13, "rank": 13, "name": "Chase Brown", "team": "CIN", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "B", "espnId": "4362238"},
    {"id": 14, "rank": 14, "name": "Omarion Hampton", "team": "LAC", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "C", "espnId": "4685382"},
    {"id": 15, "rank": 15, "name": "Devon Achane", "team": "MIA", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "C", "espnId": "4429160"},
    {"id": 16, "rank": 16, "name": "Saquon Barkley", "team": "PHI", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "C", "espnId": "3929630"},
    {"id": 17, "rank": 17, "name": "Kenneth Walker", "team": "KC", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "C", "espnId": "4567048"},
    {"id": 18, "rank": 18, "name": "Drake London", "team": "ATL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "C", "espnId": "4426502"},
    {"id": 19, "rank": 19, "name": "Brock Bowers", "team": "LV", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "C", "espnId": "4432665"},
    {"id": 20, "rank": 20, "name": "Derrick Henry", "team": "BAL", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "C", "espnId": "3043078"},
    {"id": 21, "rank": 21, "name": "A.J. Brown", "team": "NE", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "C", "espnId": "4047646"},
    {"id": 22, "rank": 22, "name": "Nico Collins", "team": "HOU", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "D", "espnId": "4258173"},
    {"id": 23, "rank": 23, "name": "Malik Nabers", "team": "NYG", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "D", "espnId": "4595348"},
    {"id": 24, "rank": 24, "name": "Jeremiyah Love", "team": "ARI", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "D", "espnId": "4870808"},
    {"id": 25, "rank": 25, "name": "Rashee Rice", "team": "KC", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "D", "espnId": "4428331"},
    {"id": 26, "rank": 26, "name": "George Pickens", "team": "DAL", "bye": 7, "pos": "WR", "posClass": "pos-wr", "tier": "D", "espnId": "4426354"},
    {"id": 27, "rank": 27, "name": "Trey McBride", "team": "ARI", "bye": 11, "pos": "TE", "posClass": "pos-te", "tier": "D", "espnId": "4361307"},
    {"id": 28, "rank": 28, "name": "Breece Hall", "team": "NYJ", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "D", "espnId": "4427366"},
    {"id": 29, "rank": 29, "name": "DeVonta Smith", "team": "PHI", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "D", "espnId": "4241478"},
    {"id": 30, "rank": 30, "name": "Chris Olave", "team": "NO", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "E", "espnId": "4361370"},
    {"id": 31, "rank": 31, "name": "Kyren Williams", "team": "LAR", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "E", "espnId": "4430737"},
    {"id": 32, "rank": 32, "name": "Javonte Williams", "team": "DAL", "bye": 7, "pos": "RB", "posClass": "pos-rb", "tier": "E", "espnId": "4361579"},
    {"id": 33, "rank": 33, "name": "Zay Flowers", "team": "BAL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "E", "espnId": "4429615"},
    {"id": 34, "rank": 34, "name": "Tee Higgins", "team": "CIN", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "E", "espnId": "4239993"},
    {"id": 35, "rank": 35, "name": "Josh Allen", "team": "BUF", "bye": 12, "pos": "QB", "posClass": "pos-qb", "tier": "E", "espnId": "3918298"},
    {"id": 36, "rank": 36, "name": "Jaylen Waddle", "team": "DEN", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "E", "espnId": "4372016"},
    {"id": 37, "rank": 37, "name": "Emeka Egbuka", "team": "TB", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "E", "espnId": "4567750"},
    {"id": 38, "rank": 38, "name": "Josh Jacobs", "team": "GB", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "E", "espnId": "4047365"},
    {"id": 39, "rank": 39, "name": "Ladd McConkey", "team": "LAC", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "E", "espnId": "4612826"},
    {"id": 40, "rank": 40, "name": "Colston Loveland", "team": "CHI", "bye": 7, "pos": "TE", "posClass": "pos-te", "tier": "E", "espnId": "4723086"},
    {"id": 41, "rank": 41, "name": "Cam Skattebo", "team": "NYG", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "E", "espnId": "4696981"},
    {"id": 42, "rank": 42, "name": "Tetairoa McMillan", "team": "CAR", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "F", "espnId": "4685472"},
    {"id": 43, "rank": 43, "name": "Garrett Wilson", "team": "NYJ", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "F", "espnId": "4569618"},
    {"id": 44, "rank": 44, "name": "Travis Etienne", "team": "NO", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "F", "espnId": "4239996"},
    {"id": 45, "rank": 45, "name": "Bucky Irving", "team": "TB", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "F", "espnId": "4596448"},
    {"id": 46, "rank": 46, "name": "Davante Adams", "team": "LAR", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "F", "espnId": "16800"},
    {"id": 47, "rank": 47, "name": "Bhayshul Tuten", "team": "JAX", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "F", "espnId": "4882093"},
    {"id": 48, "rank": 48, "name": "David Montgomery", "team": "HOU", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "F", "espnId": "4035538"},
    {"id": 49, "rank": 49, "name": "Terry McLaurin", "team": "WAS", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "F", "espnId": "3121422"},
    {"id": 50, "rank": 50, "name": "D'Andre Swift", "team": "CHI", "bye": 7, "pos": "RB", "posClass": "pos-rb", "tier": "F", "espnId": "4259545"},
    {"id": 51, "rank": 51, "name": "Jameson Williams", "team": "DET", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "F", "espnId": "4426388"},
    {"id": 52, "rank": 52, "name": "Quinshon Judkins", "team": "CLE", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "F", "espnId": "4685702"},
    {"id": 53, "rank": 53, "name": "Luther Burden", "team": "CHI", "bye": 7, "pos": "WR", "posClass": "pos-wr", "tier": "F", "espnId": "4685278"},
    {"id": 54, "rank": 54, "name": "TreVeyon Henderson", "team": "NE", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4432710"},
    {"id": 55, "rank": 55, "name": "Mike Evans", "team": "SF", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "16737"},
    {"id": 56, "rank": 56, "name": "Lamar Jackson", "team": "BAL", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "3916387"},
    {"id": 57, "rank": 57, "name": "Carnell Tate", "team": "TEN", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4871023"},
    {"id": 58, "rank": 58, "name": "Jadarian Price", "team": "SEA", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4685512"},
    {"id": 59, "rank": 59, "name": "Rome Odunze", "team": "CHI", "bye": 7, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4431299"},
    {"id": 60, "rank": 60, "name": "Brian Thomas", "team": "JAX", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4432773"},
    {"id": 61, "rank": 61, "name": "Tyler Warren", "team": "IND", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "G", "espnId": "4431459"},
    {"id": 62, "rank": 62, "name": "DJ Moore", "team": "BUF", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "3915416"},
    {"id": 63, "rank": 63, "name": "Christian Watson", "team": "GB", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4248528"},
    {"id": 64, "rank": 64, "name": "Marvin Harrison", "team": "ARI", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4432708"},
    {"id": 65, "rank": 65, "name": "Jordyn Tyson", "team": "NO", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4880281"},
    {"id": 66, "rank": 66, "name": "Drake Maye", "team": "NE", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "4431452"},
    {"id": 67, "rank": 67, "name": "Jayden Daniels", "team": "WAS", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "4426348"},
    {"id": 68, "rank": 68, "name": "Joe Burrow", "team": "CIN", "bye": 12, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "3915511"},
    {"id": 69, "rank": 69, "name": "Jaylen Warren", "team": "PIT", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4569987"},
    {"id": 70, "rank": 70, "name": "Parker Washington", "team": "JAX", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4432620"},
    {"id": 71, "rank": 71, "name": "Caleb Williams", "team": "CHI", "bye": 7, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "4431611"},
    {"id": 72, "rank": 72, "name": "Jalen Hurts", "team": "PHI", "bye": 5, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "4040715"},
    {"id": 73, "rank": 73, "name": "Tucker Kraft", "team": "GB", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "G", "espnId": "4572680"},
    {"id": 74, "rank": 74, "name": "Tony Pollard", "team": "TEN", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "3916148"},
    {"id": 75, "rank": 75, "name": "Makai Lemon", "team": "PHI", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4870795"},
    {"id": 76, "rank": 76, "name": "Rhamondre Stevenson", "team": "NE", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4569173"},
    {"id": 77, "rank": 77, "name": "Quentin Johnston", "team": "LAC", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4429025"},
    {"id": 78, "rank": 78, "name": "Jonathon Brooks", "team": "CAR", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4678008"},
    {"id": 79, "rank": 79, "name": "Alec Pierce", "team": "IND", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4360078"},
    {"id": 80, "rank": 80, "name": "Sam LaPorta", "team": "DET", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "G", "espnId": "4430027"},
    {"id": 81, "rank": 81, "name": "Trevor Lawrence", "team": "JAX", "bye": 12, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "4360310"},
    {"id": 82, "rank": 82, "name": "Jordan Addison", "team": "MIN", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4429205"},
    {"id": 83, "rank": 83, "name": "DK Metcalf", "team": "PIT", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4047650"},
    {"id": 84, "rank": 84, "name": "Michael Pittman", "team": "PIT", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4035687"},
    {"id": 85, "rank": 85, "name": "Chris Godwin", "team": "TB", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "3116165"},
    {"id": 86, "rank": 86, "name": "RJ Harvey", "team": "DEN", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4568490"},
    {"id": 87, "rank": 87, "name": "Chuba Hubbard", "team": "CAR", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4241416"},
    {"id": 88, "rank": 88, "name": "Justin Herbert", "team": "LAC", "bye": 5, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "4038941"},
    {"id": 89, "rank": 89, "name": "J.K. Dobbins", "team": "DEN", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4241985"},
    {"id": 90, "rank": 90, "name": "Rachaad White", "team": "WAS", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4697815"},
    {"id": 91, "rank": 91, "name": "Courtland Sutton", "team": "DEN", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "3128429"},
    {"id": 92, "rank": 92, "name": "Dak Prescott", "team": "DAL", "bye": 7, "pos": "QB", "posClass": "pos-qb", "tier": "G", "espnId": "2577417"},
    {"id": 93, "rank": 93, "name": "Rico Dowdle", "team": "PIT", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "G", "espnId": "4038815"},
    {"id": 94, "rank": 94, "name": "Harold Fannin", "team": "CLE", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "G", "espnId": "5083076"},
    {"id": 95, "rank": 95, "name": "Michael Wilson", "team": "ARI", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "G", "espnId": "4360761"},
    {"id": 96, "rank": 96, "name": "Josh Downs", "team": "IND", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4688813"},
    {"id": 97, "rank": 97, "name": "Kyle Pitts", "team": "ATL", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "H", "espnId": "4360248"},
    {"id": 98, "rank": 98, "name": "Stefon Diggs", "team": "WAS", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "2976212"},
    {"id": 99, "rank": 99, "name": "Blake Corum", "team": "LAR", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "4429096"},
    {"id": 100, "rank": 100, "name": "Jordan Mason", "team": "MIN", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "4360569"},
    {"id": 101, "rank": 101, "name": "Kyle Monangai", "team": "CHI", "bye": 7, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "4608686"},
    {"id": 102, "rank": 102, "name": "Jaxson Dart", "team": "NYG", "bye": 11, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "4689114"},
    {"id": 103, "rank": 103, "name": "Brock Purdy", "team": "SF", "bye": 9, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "4361741"},
    {"id": 104, "rank": 104, "name": "Wan'Dale Robinson", "team": "TEN", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4569587"},
    {"id": 105, "rank": 105, "name": "KC Concepcion", "team": "CLE", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4870653"},
    {"id": 106, "rank": 106, "name": "Bo Nix", "team": "DEN", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "4426338"},
    {"id": 107, "rank": 107, "name": "Jayden Reed", "team": "GB", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4362249"},
    {"id": 108, "rank": 108, "name": "Patrick Mahomes", "team": "KC", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "3139477"},
    {"id": 109, "rank": 109, "name": "Xavier Worthy", "team": "KC", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4683062"},
    {"id": 110, "rank": 110, "name": "Kenneth Gainwell", "team": "TB", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "4371733"},
    {"id": 111, "rank": 111, "name": "Jacory Croskey-Merritt", "team": "WAS", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "4575131"},
    {"id": 112, "rank": 112, "name": "George Kittle", "team": "SF", "bye": 9, "pos": "TE", "posClass": "pos-te", "tier": "H", "espnId": "3040151"},
    {"id": 113, "rank": 113, "name": "Matthew Stafford", "team": "LAR", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "12483"},
    {"id": 114, "rank": 114, "name": "Jared Goff", "team": "DET", "bye": 5, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "3046779"},
    {"id": 115, "rank": 115, "name": "Kyler Murray", "team": "MIN", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "3917315"},
    {"id": 116, "rank": 116, "name": "Deebo Samuel", "team": "SF", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "3126486"},
    {"id": 117, "rank": 117, "name": "Jakobi Meyers", "team": "JAX", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "3916433"},
    {"id": 118, "rank": 118, "name": "Travis Kelce", "team": "KC", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "H", "espnId": "15847"},
    {"id": 119, "rank": 119, "name": "Matthew Golden", "team": "GB", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4701936"},
    {"id": 120, "rank": 120, "name": "Aaron Jones", "team": "MIN", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "3042519"},
    {"id": 121, "rank": 121, "name": "Travis Hunter", "team": "JAX", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4685415"},
    {"id": 122, "rank": 122, "name": "Romeo Doubs", "team": "NE", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4361432"},
    {"id": 123, "rank": 123, "name": "Jalen Coker", "team": "CAR", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4695883"},
    {"id": 124, "rank": 124, "name": "Jayden Higgins", "team": "HOU", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4877706"},
    {"id": 125, "rank": 125, "name": "Jake Ferguson", "team": "DAL", "bye": 7, "pos": "TE", "posClass": "pos-te", "tier": "H", "espnId": "4242355"},
    {"id": 126, "rank": 126, "name": "Baker Mayfield", "team": "TB", "bye": 11, "pos": "QB", "posClass": "pos-qb", "tier": "H", "espnId": "3052587"},
    {"id": 127, "rank": 127, "name": "Isaiah Likely", "team": "NYG", "bye": 11, "pos": "TE", "posClass": "pos-te", "tier": "H", "espnId": "4361050"},
    {"id": 128, "rank": 128, "name": "Chris Rodriguez", "team": "JAX", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "H", "espnId": "4362619"},
    {"id": 129, "rank": 129, "name": "Mark Andrews", "team": "BAL", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "H", "espnId": "3116365"},
    {"id": 130, "rank": 130, "name": "Khalil Shakir", "team": "BUF", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "H", "espnId": "4373678"},
    {"id": 131, "rank": 131, "name": "Tyrone Tracy", "team": "NYG", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4360516"},
    {"id": 132, "rank": 132, "name": "Tyler Shough", "team": "NO", "bye": 12, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "4360689"},
    {"id": 133, "rank": 133, "name": "Dalton Kincaid", "team": "BUF", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4385690"},
    {"id": 134, "rank": 134, "name": "Rashid Shaheed", "team": "SEA", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4032473"},
    {"id": 135, "rank": 135, "name": "Woody Marks", "team": "HOU", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4429059"},
    {"id": 136, "rank": 136, "name": "Jordan Love", "team": "GB", "bye": 10, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "4036378"},
    {"id": 137, "rank": 137, "name": "Malik Willis", "team": "MIA", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "4242512"},
    {"id": 138, "rank": 138, "name": "Jonah Coleman", "team": "DEN", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4702555"},
    {"id": 139, "rank": 139, "name": "Omar Cooper Jr.", "team": "NYJ", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4723820"},
    {"id": 140, "rank": 140, "name": "Keaton Mitchell", "team": "LAC", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4596334"},
    {"id": 141, "rank": 141, "name": "Denzel Boston", "team": "CLE", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4832800"},
    {"id": 142, "rank": 142, "name": "Dallas Goedert", "team": "PHI", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "3121023"},
    {"id": 143, "rank": 143, "name": "Jalen McMillan", "team": "TB", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4430834"},
    {"id": 144, "rank": 144, "name": "Oronde Gadsden", "team": "LAC", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4595342"},
    {"id": 145, "rank": 145, "name": "De'Zhaun Stribling", "team": "SF", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4710714"},
    {"id": 146, "rank": 146, "name": "Isiah Pacheco", "team": "DET", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4361529"},
    {"id": 147, "rank": 147, "name": "Chig Okonkwo", "team": "WAS", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4360635"},
    {"id": 148, "rank": 148, "name": "Tre Tucker", "team": "LV", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4428718"},
    {"id": 149, "rank": 149, "name": "Brenton Strange", "team": "JAX", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4430539"},
    {"id": 150, "rank": 150, "name": "Tyler Allgeier", "team": "ARI", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4373626"},
    {"id": 151, "rank": 151, "name": "Tank Bigsby", "team": "PHI", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4429013"},
    {"id": 152, "rank": 152, "name": "C.J. Stroud", "team": "HOU", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "4432577"},
    {"id": 153, "rank": 153, "name": "Sam Darnold", "team": "SEA", "bye": 10, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "3912547"},
    {"id": 154, "rank": 154, "name": "Cam Ward", "team": "TEN", "bye": 5, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "4688380"},
    {"id": 155, "rank": 155, "name": "Hunter Henry", "team": "NE", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "3046439"},
    {"id": 156, "rank": 156, "name": "Daniel Jones", "team": "IND", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "3917792"},
    {"id": 157, "rank": 157, "name": "Jauan Jennings", "team": "MIN", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "3886598"},
    {"id": 158, "rank": 158, "name": "Alvin Kamara", "team": "NO", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "3054850"},
    {"id": 159, "rank": 159, "name": "Kenyon Sadiq", "team": "NYJ", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "5083315"},
    {"id": 160, "rank": 160, "name": "Dylan Sampson", "team": "CLE", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "5081397"},
    {"id": 161, "rank": 161, "name": "Zach Charbonnet", "team": "SEA", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4426385"},
    {"id": 162, "rank": 162, "name": "Jalen Nailor", "team": "LV", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4382466"},
    {"id": 163, "rank": 163, "name": "Bryce Young", "team": "CAR", "bye": 11, "pos": "QB", "posClass": "pos-qb", "tier": "I", "espnId": "4685720"},
    {"id": 164, "rank": 164, "name": "Tyjae Spears", "team": "TEN", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4428557"},
    {"id": 165, "rank": 165, "name": "T.J. Hockenson", "team": "MIN", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4036133"},
    {"id": 166, "rank": 166, "name": "Brian Robinson", "team": "ATL", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4241474"},
    {"id": 167, "rank": 167, "name": "AJ Barner", "team": "SEA", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4576297"},
    {"id": 168, "rank": 168, "name": "Juwan Johnson", "team": "NO", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "3929645"},
    {"id": 169, "rank": 169, "name": "Dalton Schultz", "team": "HOU", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "3117256"},
    {"id": 170, "rank": 170, "name": "Sean Tucker", "team": "TB", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4430871"},
    {"id": 171, "rank": 171, "name": "Tre Harris", "team": "LAC", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4686612"},
    {"id": 172, "rank": 172, "name": "Antonio Williams", "team": "WAS", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "5081432"},
    {"id": 173, "rank": 173, "name": "Kaytron Allen", "team": "WAS", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4685246"},
    {"id": 174, "rank": 174, "name": "Darnell Mooney", "team": "NYG", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4040655"},
    {"id": 175, "rank": 175, "name": "Greg Dulcich", "team": "MIA", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "I", "espnId": "4367209"},
    {"id": 176, "rank": 176, "name": "Nicholas Singleton", "team": "TEN", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "I", "espnId": "4685555"},
    {"id": 177, "rank": 177, "name": "Adonai Mitchell", "team": "NYJ", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "4597500"},
    {"id": 178, "rank": 178, "name": "Calvin Ridley", "team": "TEN", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "3925357"},
    {"id": 179, "rank": 179, "name": "Ryan Flournoy", "team": "DAL", "bye": 7, "pos": "WR", "posClass": "pos-wr", "tier": "I", "espnId": "5083754"},
    {"id": 180, "rank": 180, "name": "Emmett Johnson", "team": "KC", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4832955"},
    {"id": 181, "rank": 181, "name": "MarShawn Lloyd", "team": "GB", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4429023"},
    {"id": 182, "rank": 182, "name": "Malik Washington", "team": "MIA", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "J", "espnId": "4569603"},
    {"id": 183, "rank": 183, "name": "Tank Dell", "team": "HOU", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "J", "espnId": "4366031"},
    {"id": 184, "rank": 184, "name": "Jerry Jeudy", "team": "CLE", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "J", "espnId": "4241463"},
    {"id": 185, "rank": 185, "name": "Dontayvion Wicks", "team": "PHI", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "J", "espnId": "4428850"},
    {"id": 186, "rank": 186, "name": "Zachariah Branch", "team": "ATL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "J", "espnId": "4870612"},
    {"id": 187, "rank": 187, "name": "Mike Washington Jr.", "team": "LV", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4686658"},
    {"id": 188, "rank": 188, "name": "Dawson Knox", "team": "BUF", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "J", "espnId": "3930086"},
    {"id": 189, "rank": 189, "name": "Isaac TeSlaa", "team": "DET", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "J", "espnId": "5123663"},
    {"id": 190, "rank": 190, "name": "Ray Davis", "team": "BUF", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4429501"},
    {"id": 191, "rank": 191, "name": "Demond Claiborne", "team": "MIN", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4832846"},
    {"id": 192, "rank": 192, "name": "Gunnar Helm", "team": "TEN", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "J", "espnId": "4686728"},
    {"id": 193, "rank": 193, "name": "Chris Brooks", "team": "GB", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "3149687"},
    {"id": 194, "rank": 194, "name": "Mason Taylor", "team": "NYJ", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "J", "espnId": "4808766"},
    {"id": 195, "rank": 195, "name": "Devin Singletary", "team": "NYG", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4040761"},
    {"id": 196, "rank": 196, "name": "George Holani", "team": "SEA", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "J", "espnId": "4429835"},
    {"id": 197, "rank": 197, "name": "Germie Bernard", "team": "PIT", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4685261"},
    {"id": 198, "rank": 198, "name": "Brashard Smith", "team": "KC", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "K", "espnId": "4596602"},
    {"id": 199, "rank": 199, "name": "Terrance Ferguson", "team": "LAR", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "4570037"},
    {"id": 200, "rank": 200, "name": "Elijah Sarratt", "team": "BAL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "5088338"},
    {"id": 201, "rank": 201, "name": "David Njoku", "team": "LAC", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "3123076"},
    {"id": 202, "rank": 202, "name": "Aaron Rodgers", "team": "PIT", "bye": 9, "pos": "QB", "posClass": "pos-qb", "tier": "K", "espnId": "8439"},
    {"id": 203, "rank": 203, "name": "Kayshon Boutte", "team": "NE", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4429022"},
    {"id": 204, "rank": 204, "name": "Chris Bell", "team": "MIA", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4869961"},
    {"id": 205, "rank": 205, "name": "Braelon Allen", "team": "NYJ", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "K", "espnId": "4685247"},
    {"id": 206, "rank": 206, "name": "Jacoby Brissett", "team": "ARI", "bye": 11, "pos": "QB", "posClass": "pos-qb", "tier": "K", "espnId": "2578570"},
    {"id": 207, "rank": 207, "name": "Elijah Arroyo", "team": "SEA", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "4678006"},
    {"id": 208, "rank": 208, "name": "Ollie Gordon II", "team": "MIA", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "K", "espnId": "4711533"},
    {"id": 209, "rank": 209, "name": "Brandon Aiyuk", "team": "SF", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4360438"},
    {"id": 210, "rank": 210, "name": "Pat Freiermuth", "team": "PIT", "bye": 9, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "4361411"},
    {"id": 211, "rank": 211, "name": "Cole Kmet", "team": "CHI", "bye": 7, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "4258595"},
    {"id": 212, "rank": 212, "name": "Jaylin Noel", "team": "HOU", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4586312"},
    {"id": 213, "rank": 213, "name": "Troy Franklin", "team": "DEN", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4431280"},
    {"id": 214, "rank": 214, "name": "Jaydon Blue", "team": "DAL", "bye": 7, "pos": "RB", "posClass": "pos-rb", "tier": "K", "espnId": "4685279"},
    {"id": 215, "rank": 215, "name": "Kimani Vidal", "team": "LAC", "bye": 5, "pos": "RB", "posClass": "pos-rb", "tier": "K", "espnId": "4430968"},
    {"id": 216, "rank": 216, "name": "Mike Gesicki", "team": "CIN", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "3116164"},
    {"id": 217, "rank": 217, "name": "Cade Otton", "team": "TB", "bye": 11, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "4243331"},
    {"id": 218, "rank": 218, "name": "Cooper Kupp", "team": "SEA", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "2977187"},
    {"id": 219, "rank": 219, "name": "Pat Bryant", "team": "DEN", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "K", "espnId": "4600981"},
    {"id": 220, "rank": 220, "name": "Najee Harris", "team": "", "bye": "-", "pos": "RB", "posClass": "pos-rb", "tier": "K", "espnId": "4241457"},
    {"id": 221, "rank": 221, "name": "Eli Stowers", "team": "PHI", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "K", "espnId": "4431574"},
    {"id": 222, "rank": 222, "name": "Ja'Kobi Lane", "team": "BAL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "L", "espnId": "4870847"},
    {"id": 223, "rank": 223, "name": "Ted Hurst", "team": "TB", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "L", "espnId": "5220680"},
    {"id": 224, "rank": 224, "name": "Eli Stowers", "team": "", "bye": "-", "pos": "TE", "posClass": "pos-te", "tier": "L", "espnId": "4431574"},
    {"id": 225, "rank": 225, "name": "Elic Ayomanor", "team": "TEN", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "L", "espnId": "4883647"},
    {"id": 226, "rank": 226, "name": "Geno Smith", "team": "NYJ", "bye": 12, "pos": "QB", "posClass": "pos-qb", "tier": "L", "espnId": "15864"},
    {"id": 227, "rank": 227, "name": "Kaelon Black", "team": "SF", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "L", "espnId": "4696044"},
    {"id": 228, "rank": 228, "name": "Jordan James", "team": "SF", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "L", "espnId": "4685397"},
    {"id": 229, "rank": 229, "name": "Ja'Tavion Sanders", "team": "CAR", "bye": 11, "pos": "TE", "posClass": "pos-te", "tier": "L", "espnId": "4431588"},
    {"id": 230, "rank": 230, "name": "Keenan Allen", "team": "", "bye": "-", "pos": "WR", "posClass": "pos-wr", "tier": "L", "espnId": "15818"},
    {"id": 231, "rank": 231, "name": "Darius Slayton", "team": "NYG", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "L", "espnId": "3916945"},
    {"id": 232, "rank": 232, "name": "Fernando Mendoza", "team": "LV", "bye": 10, "pos": "QB", "posClass": "pos-qb", "tier": "L", "espnId": "4837248"},
    {"id": 233, "rank": 233, "name": "Adam Randall", "team": "BAL", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "L", "espnId": "4685526"},
    {"id": 234, "rank": 234, "name": "Emanuel Wilson", "team": "SEA", "bye": 10, "pos": "RB", "posClass": "pos-rb", "tier": "L", "espnId": "4887558"},
    {"id": 235, "rank": 235, "name": "Calvin Austin", "team": "NYG", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "L", "espnId": "4243389"},
    {"id": 236, "rank": 236, "name": "Ty Johnson", "team": "BUF", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "3915411"},
    {"id": 237, "rank": 237, "name": "Malachi Fields", "team": "NYG", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4682648"},
    {"id": 238, "rank": 238, "name": "James Conner", "team": "ARI", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "3045147"},
    {"id": 239, "rank": 239, "name": "Luke McCaffrey", "team": "WAS", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4426948"},
    {"id": 240, "rank": 240, "name": "Samaje Perine", "team": "CIN", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "3116389"},
    {"id": 241, "rank": 241, "name": "Chimere Dike", "team": "TEN", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4431268"},
    {"id": 242, "rank": 242, "name": "Keon Coleman", "team": "BUF", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4635008"},
    {"id": 243, "rank": 243, "name": "Cyrus Allen", "team": "KC", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4912218"},
    {"id": 244, "rank": 244, "name": "Jack Bech", "team": "LV", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4603186"},
    {"id": 245, "rank": 245, "name": "Tory Horton", "team": "SEA", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4597703"},
    {"id": 246, "rank": 246, "name": "Justice Hill", "team": "BAL", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "4038441"},
    {"id": 247, "rank": 247, "name": "Kendrick Bourne", "team": "ARI", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "3045523"},
    {"id": 248, "rank": 248, "name": "Christian Kirk", "team": "SF", "bye": 9, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "3895856"},
    {"id": 249, "rank": 249, "name": "Tez Johnson", "team": "TB", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4608810"},
    {"id": 250, "rank": 250, "name": "DJ Giddens", "team": "IND", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "4874509"},
    {"id": 251, "rank": 251, "name": "Bryce Lance", "team": "NO", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4879276"},
    {"id": 252, "rank": 252, "name": "Tyreek Hill", "team": "", "bye": "-", "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "3116406"},
    {"id": 253, "rank": 253, "name": "Tua Tagovailoa", "team": "ATL", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "M", "espnId": "4241479"},
    {"id": 254, "rank": 254, "name": "Isaiah Davis", "team": "NYJ", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "4695404"},
    {"id": 255, "rank": 255, "name": "Tyquan Thornton", "team": "KC", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "M", "espnId": "4362921"},
    {"id": 256, "rank": 256, "name": "Kendre Miller", "team": "NO", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "M", "espnId": "4599739"},
    {"id": 257, "rank": 257, "name": "Darnell Washington", "team": "PIT", "bye": 9, "pos": "TE", "posClass": "pos-te", "tier": "N", "espnId": "4430802"},
    {"id": 258, "rank": 258, "name": "Skyler Bell", "team": "BUF", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4683153"},
    {"id": 259, "rank": 259, "name": "Rashod Bateman", "team": "BAL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4360939"},
    {"id": 260, "rank": 260, "name": "Caleb Douglas", "team": "MIA", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4869645"},
    {"id": 261, "rank": 261, "name": "Cedric Tillman", "team": "CLE", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4369863"},
    {"id": 262, "rank": 262, "name": "Chris Brazzell II", "team": "CAR", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "5091739"},
    {"id": 263, "rank": 263, "name": "Treylon Burks", "team": "WAS", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4567156"},
    {"id": 264, "rank": 264, "name": "Devaughn Vele", "team": "NO", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4569559"},
    {"id": 265, "rank": 265, "name": "Isaac Guerendo", "team": "SF", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "N", "espnId": "4372561"},
    {"id": 266, "rank": 266, "name": "Seth McGowan", "team": "IND", "bye": 14, "pos": "RB", "posClass": "pos-rb", "tier": "N", "espnId": "4686468"},
    {"id": 267, "rank": 267, "name": "Evan Engram", "team": "DEN", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "N", "espnId": "3051876"},
    {"id": 268, "rank": 268, "name": "Xavier Legette", "team": "CAR", "bye": 11, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4430034"},
    {"id": 269, "rank": 269, "name": "Colby Parkinson", "team": "LAR", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "N", "espnId": "4242557"},
    {"id": 270, "rank": 270, "name": "Kaleb Johnson", "team": "PIT", "bye": 9, "pos": "RB", "posClass": "pos-rb", "tier": "N", "espnId": "4819231"},
    {"id": 271, "rank": 271, "name": "Justin Joly", "team": "DEN", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "N", "espnId": "4912052"},
    {"id": 272, "rank": 272, "name": "Max Klare", "team": "LAR", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "N", "espnId": "4833029"},
    {"id": 273, "rank": 273, "name": "Andrei Iosivas", "team": "CIN", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "N", "espnId": "4368003"},
    {"id": 274, "rank": 274, "name": "Trey Benson", "team": "ARI", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "N", "espnId": "4429275"},
    {"id": 275, "rank": 275, "name": "Shedeur Sanders", "team": "CLE", "bye": 10, "pos": "QB", "posClass": "pos-qb", "tier": "N", "espnId": "4432762"},
    {"id": 276, "rank": 276, "name": "Jaylen Wright", "team": "MIA", "bye": 6, "pos": "RB", "posClass": "pos-rb", "tier": "O", "espnId": "4682745"},
    {"id": 277, "rank": 277, "name": "Hollywood Brown", "team": "PHI", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4241372"},
    {"id": 278, "rank": 278, "name": "Michael Mayer", "team": "LV", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4429086"},
    {"id": 279, "rank": 279, "name": "Noah Gray", "team": "KC", "bye": 6, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4240472"},
    {"id": 280, "rank": 280, "name": "Deshaun Watson", "team": "CLE", "bye": 10, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "3122840"},
    {"id": 281, "rank": 281, "name": "Michael Penix", "team": "ATL", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4360423"},
    {"id": 282, "rank": 282, "name": "Eli Raridon", "team": "NE", "bye": 14, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4831959"},
    {"id": 283, "rank": 283, "name": "Devin Neal", "team": "NO", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "O", "espnId": "4682652"},
    {"id": 284, "rank": 284, "name": "Zavion Thomas", "team": "CHI", "bye": 7, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4869748"},
    {"id": 285, "rank": 285, "name": "LeQuint Allen", "team": "JAX", "bye": 12, "pos": "RB", "posClass": "pos-rb", "tier": "O", "espnId": "4911851"},
    {"id": 286, "rank": 286, "name": "Jake Tonges", "team": "SF", "bye": 9, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4259147"},
    {"id": 287, "rank": 287, "name": "Jalen Tolbert", "team": "MIA", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4249417"},
    {"id": 288, "rank": 288, "name": "Mack Hollins", "team": "NE", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "2991662"},
    {"id": 289, "rank": 289, "name": "Konata Mumpfield", "team": "LAR", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4710855"},
    {"id": 290, "rank": 290, "name": "Brenen Thompson", "team": "LAC", "bye": 5, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4685553"},
    {"id": 291, "rank": 291, "name": "Erick All", "team": "CIN", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4427834"},
    {"id": 292, "rank": 292, "name": "Charlie Kolar", "team": "LAC", "bye": 5, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4241263"},
    {"id": 293, "rank": 293, "name": "Olamide Zaccheaus", "team": "ATL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "3917914"},
    {"id": 294, "rank": 294, "name": "Jordan Whittington", "team": "LAR", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4569382"},
    {"id": 295, "rank": 295, "name": "Noah Fant", "team": "NO", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4036131"},
    {"id": 296, "rank": 296, "name": "Trevor Etienne", "team": "CAR", "bye": 11, "pos": "RB", "posClass": "pos-rb", "tier": "O", "espnId": "4685350"},
    {"id": 297, "rank": 297, "name": "Jaylin Lane", "team": "WAS", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4602667"},
    {"id": 298, "rank": 298, "name": "Kirk Cousins", "team": "LV", "bye": 10, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "14880"},
    {"id": 299, "rank": 299, "name": "Carson Beck", "team": "ARI", "bye": 11, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4430841"},
    {"id": 300, "rank": 300, "name": "Luke Musgrave", "team": "GB", "bye": 10, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4428085"},
    {"id": 301, "rank": 301, "name": "Theo Johnson", "team": "NYG", "bye": 11, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4429148"},
    {"id": 302, "rank": 302, "name": "Drew Allar", "team": "PIT", "bye": 9, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4714771"},
    {"id": 303, "rank": 303, "name": "Tutu Atwell", "team": "MIA", "bye": 6, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4360797"},
    {"id": 304, "rank": 304, "name": "Joshua Palmer", "team": "BUF", "bye": 12, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4242433"},
    {"id": 305, "rank": 305, "name": "Malik Davis", "team": "DAL", "bye": 7, "pos": "RB", "posClass": "pos-rb", "tier": "O", "espnId": "4240603"},
    {"id": 306, "rank": 306, "name": "Anthony Richardson", "team": "IND", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4429084"},
    {"id": 307, "rank": 307, "name": "Jameis Winston", "team": "NYG", "bye": 11, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "2969939"},
    {"id": 308, "rank": 308, "name": "Marcus Mariota", "team": "WAS", "bye": 14, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "2576980"},
    {"id": 309, "rank": 309, "name": "Cade Klubnik", "team": "NYJ", "bye": 12, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4685413"},
    {"id": 310, "rank": 310, "name": "Oscar Delp", "team": "NO", "bye": 12, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4702559"},
    {"id": 311, "rank": 311, "name": "Dont'e Thornton Jr.", "team": "LV", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4432775"},
    {"id": 312, "rank": 312, "name": "J.J. McCarthy", "team": "MIN", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4433970"},
    {"id": 313, "rank": 313, "name": "Mac Jones", "team": "SF", "bye": 9, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4241464"},
    {"id": 314, "rank": 314, "name": "Luke Schoonmaker", "team": "DAL", "bye": 7, "pos": "TE", "posClass": "pos-te", "tier": "O", "espnId": "4372096"},
    {"id": 315, "rank": 315, "name": "Justin Fields", "team": "KC", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4362887"},
    {"id": 316, "rank": 316, "name": "Jahan Dotson", "team": "ATL", "bye": 14, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4361409"},
    {"id": 317, "rank": 317, "name": "Ty Simpson", "team": "LAR", "bye": 6, "pos": "QB", "posClass": "pos-qb", "tier": "O", "espnId": "4685522"},
    {"id": 318, "rank": 318, "name": "Isaiah Bond", "team": "CLE", "bye": 10, "pos": "WR", "posClass": "pos-wr", "tier": "O", "espnId": "4808839"},
    {"id": 1000, "rank": 145, "name": "Brandon Aubrey", "team": "DAL", "bye": 7, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "3953687"},
    {"id": 1001, "rank": 168, "name": "Ka'imi Fairbairn", "team": "HOU", "bye": 14, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "2971573"},
    {"id": 1002, "rank": 174, "name": "Cameron Dicker", "team": "LAC", "bye": 5, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4362081"},
    {"id": 1003, "rank": 177, "name": "Jason Myers", "team": "SEA", "bye": 10, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "2473037"},
    {"id": 1004, "rank": 184, "name": "Cam Little", "team": "JAC", "bye": "-", "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4686361"},
    {"id": 1005, "rank": 191, "name": "Eddy Pineiro", "team": "SF", "bye": 9, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4034949"},
    {"id": 1006, "rank": 196, "name": "Tyler Loop", "team": "BAL", "bye": 14, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4697745"},
    {"id": 1007, "rank": 211, "name": "Evan McPherson", "team": "CIN", "bye": 12, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4360234"},
    {"id": 1008, "rank": 216, "name": "Cairo Santos", "team": "CHI", "bye": 7, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "17427"},
    {"id": 1009, "rank": 219, "name": "Jake Bates", "team": "DET", "bye": 5, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4689936"},
    {"id": 1010, "rank": 220, "name": "Andy Borregales", "team": "NE", "bye": 14, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4569923"},
    {"id": 1011, "rank": 223, "name": "Harrison Mevis", "team": "LAR", "bye": 6, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4574716"},
    {"id": 1012, "rank": 224, "name": "Chase McLaughlin", "team": "TB", "bye": 11, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "3150744"},
    {"id": 1013, "rank": 233, "name": "Chris Boswell", "team": "PIT", "bye": 9, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "17372"},
    {"id": 1014, "rank": 238, "name": "Harrison Butker", "team": "KC", "bye": 6, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "3055899"},
    {"id": 1015, "rank": 240, "name": "Will Reichard", "team": "MIN", "bye": 6, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4567104"},
    {"id": 1016, "rank": 246, "name": "Wil Lutz", "team": "DEN", "bye": 14, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "2985659"},
    {"id": 1017, "rank": 252, "name": "Charlie Smyth", "team": "NO", "bye": 12, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "5208518"},
    {"id": 1018, "rank": 266, "name": "Jake Elliott", "team": "PHI", "bye": 5, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "3050478"},
    {"id": 1019, "rank": 280, "name": "Blake Grupe", "team": "IND", "bye": 14, "pos": "K", "posClass": "pos-k", "tier": "O", "espnId": "4259619"},
    {"id": 1020, "rank": 150, "name": "Houston Texans DST", "team": "HOU", "bye": 14, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1021, "rank": 159, "name": "Denver Broncos DST", "team": "DEN", "bye": 14, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1022, "rank": 162, "name": "Seattle Seahawks DST", "team": "SEA", "bye": 10, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1023, "rank": 171, "name": "Los Angeles Rams DST", "team": "LAR", "bye": 6, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1024, "rank": 173, "name": "Philadelphia Eagles DST", "team": "PHI", "bye": 5, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1025, "rank": 190, "name": "Minnesota Vikings DST", "team": "MIN", "bye": 6, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1026, "rank": 197, "name": "Los Angeles Chargers DST", "team": "LAC", "bye": 5, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1027, "rank": 202, "name": "Baltimore Ravens DST", "team": "BAL", "bye": 14, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1028, "rank": 218, "name": "New England Patriots DST", "team": "NE", "bye": 14, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1029, "rank": 223, "name": "Pittsburgh Steelers DST", "team": "PIT", "bye": 9, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1030, "rank": 224, "name": "Jacksonville Jaguars DST", "team": "JAX", "bye": 12, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1031, "rank": 232, "name": "Green Bay Packers DST", "team": "GB", "bye": 10, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1032, "rank": 238, "name": "Kansas City Chiefs DST", "team": "KC", "bye": 6, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1033, "rank": 245, "name": "Cleveland Browns DST", "team": "CLE", "bye": 10, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1034, "rank": 248, "name": "Detroit Lions DST", "team": "DET", "bye": 5, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1035, "rank": 250, "name": "Chicago Bears DST", "team": "CHI", "bye": 7, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1036, "rank": 255, "name": "Buffalo Bills DST", "team": "BUF", "bye": 12, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1037, "rank": 260, "name": "Tampa Bay Buccaneers DST", "team": "TB", "bye": 11, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1038, "rank": 262, "name": "San Francisco 49ers DST", "team": "SF", "bye": 9, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1039, "rank": 274, "name": "Indianapolis Colts DST", "team": "IND", "bye": 14, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1040, "rank": 276, "name": "New Orleans Saints DST", "team": "NO", "bye": 12, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1041, "rank": 277, "name": "Tennessee Titans DST", "team": "TEN", "bye": 5, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1042, "rank": 281, "name": "Cincinnati Bengals DST", "team": "CIN", "bye": 12, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1043, "rank": 285, "name": "New York Jets DST", "team": "NYJ", "bye": 12, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1044, "rank": 290, "name": "Dallas Cowboys DST", "team": "DAL", "bye": 7, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1045, "rank": 294, "name": "Las Vegas Raiders DST", "team": "LV", "bye": 10, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null},
    {"id": 1046, "rank": 300, "name": "Atlanta Falcons DST", "team": "ATL", "bye": 14, "pos": "DST", "posClass": "pos-dst", "tier": "O", "espnId": null}
];
